//
//  FakeBrazilianCompanies.swift
//  PasseiOAB
//
//  Created by Vagner Oliveira on 16/11/23.
//

import Foundation

public class FakeBrazilianCompanies: FalsifiedDataProtocol {
    public typealias Value = String
    
    public var value: Value {
        [
            "Acme Comércio Ltda",
            "BrasilTech Soluções S.A.",
            "Vanguarda Consultoria e Serviços Ltda",
            "Sistemas Integrados do Brasil Ltda",
            "Central Distribuidora de Produtos S.A.",
            "Mega Construções Ltda",
            "Excelência Consultoria Empresarial S.A.",
            "VisionTech Tecnologia e Informática Ltda",
            "GreenWorld Energias Renováveis S.A.",
            "Innovate Marketing Digital Ltda",
            "MasterFood Indústria e Comércio S.A.",
            "MacroLogística Transportes Ltda",
            "QualiService Consultoria Ltda",
            "PrintExpress Gráfica e Editora S.A.",
            "AgileSoft Desenvolvimento de Software Ltda",
            "TopMóveis Indústria e Comércio S.A.",
            "SeguroFácil Corretora de Seguros Ltda",
            "TerraNova Incorporadora e Construtora S.A.",
            "Suprimentos Expresso Ltda",
            "SolutionIT Tecnologia da Informação S.A.",
            "MetaProjetos Engenharia Ltda",
            "DataWeb Soluções Digitais Ltda",
            "EcoVida Ambiental S.A.",
            "TradiçãoAlimentos Indústria e Comércio Ltda",
            "MaxVendas Representações Comerciais S.A.",
            "PlanetaAgro Agropecuária Ltda",
            "Optimum Consultoria e Serviços Ltda",
            "GloboLog Transportadora e Logística Ltda",
            "GoldenTech Soluções Tecnológicas S.A.",
            "Equilibrio Saúde e Bem-Estar Ltda",
            "FastDelivery Logística e Transportes Ltda",
            "AllianceTech Consultoria e Soluções S.A.",
            "MagnoComércio Importação e Exportação S.A.",
            "StarQuality Consultoria Empresarial Ltda",
            "InfraMax Engenharia e Construção S.A.",
            "TopTec Informática e Tecnologia Ltda",
            "Fortaleza Segurança e Vigilância Ltda",
            "PrimeChoice Consultoria e Serviços S.A.",
            "VivaBem Saúde e Bem-Estar Ltda",
            "MegaLog Transportes e Logística Ltda",
            "TechSolutions Soluções Tecnológicas Ltda",
            "MundoVida Produtos Naturais Ltda",
            "VisionaryTech Tecnologia e Inovação S.A.",
            "Solaris Energias Renováveis S.A.",
            "PrimeSolutions Consultoria e Serviços Ltda",
            "MasterBuild Construtora e Incorporadora Ltda",
            "VerdeVivo Meio Ambiente e Sustentabilidade S.A.",
            "DynamicSoft Desenvolvimento de Software S.A.",
            "SoftInnovate Tecnologia e Inovação Ltda",
            "EcoTech Soluções Ambientais Ltda",
            "AlphaLogistics Transportes e Distribuição S.A.",
            "SmartMind Consultoria e Tecnologia Ltda",
            "FastTech Soluções Tecnológicas Ltda",
            "SecureNet Segurança Digital Ltda",
            "InnovaGestão Consultoria Empresarial Ltda",
            "SmartSpace Soluções Imobiliárias S.A.",
            "MaxiFarma Farmácias e Medicamentos Ltda",
            "GlobalLink Consultoria e Serviços S.A.",
            "ExcelTech Tecnologia e Informática Ltda",
            "VerdeVida Produtos Naturais e Orgânicos S.A.",
            "AquaTech Soluções Aquáticas Ltda",
            "GreenLog Transportes e Logística S.A.",
            "FutureVision Consultoria e Soluções Ltda",
            "TechNexus Tecnologia e Inovação S.A.",
            "LogiMax Logística e Transportes Ltda",
            "PlanetaVerde Sustentabilidade Ltda",
            "GreenSolutions Soluções Ambientais S.A.",
            "GigaNet Soluções em Redes Ltda",
            "InnovaMinds Consultoria e Tecnologia Ltda",
            "GloboTech Soluções Tecnológicas Ltda",
            "QualityLife Saúde e Bem-Estar Ltda",
            "InfoVision Tecnologia e Informática S.A.",
            "FastTrade Comércio Exterior Ltda",
            "SolidarityTech Tecnologia Solidária Ltda",
            "VisionLogistics Transportes e Logística Ltda",
            "SkyHigh Aviação e Transportes Aéreos S.A.",
            "GlobalNet Soluções em Redes S.A.",
            "NatureLife Produtos Naturais Ltda",
            "PowerTech Energia Sustentável Ltda",
            "PrimeLink Consultoria e Serviços Ltda",
            "SecureData Soluções em Segurança S.A.",
            "DynamicLogistics Transportes e Logística Ltda",
            "FutureNet Soluções Digitais S.A.",
            "SmartTrade Comércio Eletrônico Ltda",
            "WorldWide Solutions Consultoria e Serviços S.A.",
            "TechNest Tecnologia e Inovação Ltda",
            "MundoVerde Produtos Naturais Ltda",
            "InovaMind Consultoria e Tecnologia Ltda",
            "AlphaTech Tecnologia e Inovação S.A.",
            "EcoGreen Soluções Sustentáveis Ltda",].randomElement() ?? "AlphaTech Tecnologia e Inovação S.A."
    }
    
    required public init() {}
}
